#ifndef APPLICATION_H
#define APPLICATION_H

#include <hal/constants/all.h>

// Also see the following files generated by SMT32CubeMX : 
//   include/stm32u0xx_hal_conf.h

#define APP_UCDM_MAX_REGISTERS              32
#define APP_UCDM_SPAN_MAX_COUNT             0
#define APP_ENABLE_LIBVERSION_DESCRIPTORS   0

/**
 * @name Application Descriptors Configuration
 * 
 * Various descriptrs used to identify the application. For USB enumeration, 
 * the following descriptors must be minimally specified : 
 * 
 *  - APP_DESCRIPTOR_VENDOR_NAME : USB Device Manufacturer
 *  - APP_DESCRIPTOR_HARDWARE_NAME : USB Product Name
 * 
 */
/**@{*/
#define APP_DESCRIPTOR_VENDOR_NAME          "EBS Development"
#define APP_DESCRIPTOR_VENDOR_URL           "https://github.com/ebs-universe"

#define APP_DESCRIPTOR_HARDWARE_NAME        "CH32V003F4P6_EVT"
#define APP_DESCRIPTOR_HARDWARE_REVISION    "R0"
#define APP_DESCRIPTOR_HARDWARE_VARIANT     ""    

#define APP_DESCRIPTOR_FIRMWARE_NAME        "EBS Platform Development Stack"
#define APP_DESCRIPTOR_FIRMWARE_REVISION    "9.9.9"
/**@}*/

/**
 * @name Application GPIO Configuration
 */
/**@{*/   
    #define APP_ENABLE_GPIO            1
/**@}*/ 

/**
 * @name Application Systick and Time Configuration
 */
/**@{*/   
    #define APP_ENABLE_SYSTICK         1
    #define APP_USE_CORE_SYSTICK       1
    #define APP_ENABLE_TIME_CRON       1
    #define APP_ENABLE_TIME_SYNC       1
    #define APP_ENABLE_RTC             0
    #define APP_ENABLE_RTC_1HZ_OUT     0
    #define APP_ENABLE_QDELAY          1 
/**@}*/ 

/**
 * @name Application Device ID Configuration
 */
/**@{*/   
    #define APP_ENABLE_ID               1
/**@}*/ 

/**
 * @name Application Common Infrastructure Configuration
 */
/**@{*/   
    #define APP_ENABLE_OUTPUT_BLINK     1
    #define BLINK_GPIO                  GPIO_LED1
    #define BLINK_POLARITY              0

    #define APP_ENABLE_OUTPUT_ERROR     1
    #define ERROR_GPIO                  GPIO_LED2
    #define ERROR_POLARITY              0
/**@}*/

/**
 * @name TM1637 Configuration
 */
/**@{*/   
    #define APP_ENABLE_TM1637           1
    #define TM1637_NUM_DIGITS           6
    #define TM1637_SINGLETON            1
    #define TM1637_IMPL_SM              0
/**@}*/

#endif

